
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 20.6.0 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/local/Cellar/gcc/13.2.0/bin/gcc-13 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/local/Cellar/gcc/13.2.0/bin/g++-13 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rMBPRC"
      binary: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rMBPRC"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: "11.7"
      CMAKE_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rMBPRC'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/Cellar/cmake/3.29.0/bin/ctest -f Makefile cmTC_edc7e/fast
        Test project /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rMBPRC
        No tests were found!!!
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /usr/local/Cellar/gcc/13.2.0/bin/gcc-13"
    directories:
      source: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rRHGhj"
      binary: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rRHGhj"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: "11.7"
      CMAKE_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rRHGhj'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/Cellar/cmake/3.29.0/bin/ctest -f Makefile cmTC_f989c/fast
        Test project /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rRHGhj
        No tests were found!!!
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KKqEeG"
      binary: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KKqEeG"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: "11.7"
      CMAKE_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KKqEeG'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/Cellar/cmake/3.29.0/bin/ctest -f Makefile cmTC_06943/fast
        Test project /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-KKqEeG
        No tests were found!!!
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working CXX compiler: /usr/local/Cellar/gcc/13.2.0/bin/g++-13"
    directories:
      source: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rlLqwL"
      binary: "/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rlLqwL"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: "11.7"
      CMAKE_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk"
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rlLqwL'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/Cellar/cmake/3.29.0/bin/ctest -f Makefile cmTC_5e24d/fast
        Test project /Users/yang/Documents/School/Seneca/3rd_Semester/OOP244/week10/WS09/WS09/lab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rlLqwL
        No tests were found!!!
        
      exitCode: 0
...
